### ISSUE TITLE
[BUG] 使用`@import`语句导入自己的`.less`样式表时遇到异常

### ISSUE THREAD

**Issue by van-lee-fxp** [shd101wyy/vscode-markdown-preview-enhanced#1823]
以前版本的`markdown-previwew-enhanced`插件能够支持通过`@import`语句直接通过markdown源文件导入自己的`.less`样式表。但是升级到`0.8.4`版之后，自己导入的样式表不再能生效，且产生报错。

我写markdown文档时时会在每个markdown源文件的开头加上如下的`@import`语句。

```
@import "D:\New Homeland\Standards\Stylesheet\article\article-light.less"
```

以前版本都正常，但是升级到`0.8.4`版本后，预览时在`@import`语句插入的位置位置会出现如下错误提示，且导入的样式表没有生效——

```
![@embedding](D:\New Homeland\Standards\Stylesheet\article\article-light.less){error=“PHByZSBjbGFzcz0ibGFuZ3VhZ2UtdGV4dCI+PGNvZGU+SW52YWxpZENoYXJhY3RlckVycm9yOiBJbnZhbGlkIGNoYXJhY3RlcjwvY29kZT48L3ByZT4gIA==”}
```

![Code_oIPk2X0uGf](https://github.com/shd101wyy/vscode-markdown-preview-enhanced/assets/146909397/357687b5-31b5-446c-a112-faeeeeaa12fa)

**Environment**
- OS: Windows 11
- VSCode: 1.83.0
- Markdown Preview Enhanced: 0.8.4

**Comment by shd101wyy** [comment]
Ok 我找个时间修复下

**Comment by shd101wyy** [comment]
@van-lee-fxp 我刚才测试了下我没有问题。你发我一个可以复现这个问题的 zip？

**Comment by shd101wyy** [comment]
`PHByZSBjbGFzcz0ibGFuZ3VhZ2UtdGV4dCI+PGNvZGU+SW52YWxpZENoYXJhY3RlckVycm9yOiBJbnZhbGlkIGNoYXJhY3RlcjwvY29kZT48L3ByZT4gIA==` 这段是 base64，decode 完说的是

```
<pre class="language-text"><code>InvalidCharacterError: Invalid character</code></pre>  
```

**Comment by van-lee-fxp** [comment]
[mpe-problem.zip](https://github.com/shd101wyy/vscode-markdown-preview-enhanced/files/12857257/mpe-problem.zip)

好的，我将我遇到问题的Markdown文件，经过我自己修改后的`parser.js`文件还有我试图导入的样式表文件一并发给你。样式表文件位于`article`文件夹里，这个`.less`文件是我根据之前版本Markdown Preview Enhanced中的自带样式`github.less`修改而成的，里面用到的一些字体是我在本地安装使用的。

**Comment by van-lee-fxp** [comment]
给源文件添加样式表的命令我是通过`parser.js`脚本(全局的)加入的，样式表文件在我电脑上的本地存放目录是`D:\New Homeland\Standards\Stylesheet\article\article-light.less`

**Comment by van-lee-fxp** [comment]
原来的导出效果我附一个PDF

[markdown简史.pdf](https://github.com/shd101wyy/vscode-markdown-preview-enhanced/files/12857342/markdown.pdf)

**Comment by shd101wyy** [comment]
你这个太大了 :joy: 

你试试把那个 `.less` 文件里面的内容改成 

```less
.markdown-preview.markdown-preview {
   background-color: blue !important;
}
```

然后看看预览样式能不能生效？

**Comment by van-lee-fxp** [comment]
我按照你的提示将`article-light.less`文件的内容全部注释掉然后替换成你给的那一段，但是仍然会看到一样的错误信息。

接着我试了一下把文件移动到markdown的同级目录下，把脚本自动添加`@import`语句的部分去掉，然后自己在文档里写`@import`语句，但是当我输入到`@import`后面引号里的文件目录时，VSCode的右下角开始不断出现错误弹窗，弹窗的内容和上面那段Base64解码出来的内容一样，是`InvalidCharacterError: Invalid character`.

**Comment by van-lee-fxp** [comment]
具体情况参考这个视频

https://github.com/shd101wyy/vscode-markdown-preview-enhanced/assets/146909397/b4503f15-81fd-45fa-b7e1-1f3441bd8735

**Comment by van-lee-fxp** [comment]
我也猜测会不会和我对`parser.js`脚本做出的改动有关，然后我把`parser.js`脚本去掉了，但是重新测试尝试输入`@import`语句时，问题还是存在，仍然是只要一输入到引号里的内容，不管输了什么，不管输入的文件地址是否有效，右下角都会不断出现弹窗，弹窗的内容都是一样的。目前推测问题和脚本应该无关/

**Comment by shd101wyy** [comment]
你打开 Help -> Toggle Developer Tools 然后把详细的 console 中的报错信息发一下？

**Comment by van-lee-fxp** [comment]
好的，我已经调出了开发者工具，我把开发者工具显示的截图发一下——

![ZANrOOZerl](https://github.com/shd101wyy/vscode-markdown-preview-enhanced/assets/146909397/b9b7dae3-28ab-46b9-aae7-c029863e1d63)

**Comment by van-lee-fxp** [comment]
具体的报错信息如下

```
log.ts:441   ERR [Extension Host] InvalidCharacterError: Invalid character
	at new DOMException (node:internal/per_context/domexception:53:5)
	at __node_internal_ (node:internal/util:526:10)
	at atob (node:buffer:1303:13)
	at e.renderer.rules.image (c:\Users\litra\.vscode\extensions\shd101wyy.markdown-preview-enhanced-0.8.4\out\native\extension.js:1083:16686)
	at g6.renderInline (c:\Users\litra\.vscode\extensions\shd101wyy.markdown-preview-enhanced-0.8.4\out\native\extension.js:313:139)
	at g6.render (c:\Users\litra\.vscode\extensions\shd101wyy.markdown-preview-enhanced-0.8.4\out\native\extension.js:314:138)
	at jC.render (c:\Users\litra\.vscode\extensions\shd101wyy.markdown-preview-enhanced-0.8.4\out\native\extension.js:316:41992)
	at Nh.parseMD (c:\Users\litra\.vscode\extensions\shd101wyy.markdown-preview-enhanced-0.8.4\out\native\extension.js:1389:1585)
	at async Nh.generateHTMLTemplateForPreview (c:\Users\litra\.vscode\extensions\shd101wyy.markdown-preview-enhanced-0.8.4\out\native\extension.js:1193:2448)
	at async bs.initPreview (c:\Users\litra\.vscode\extensions\shd101wyy.markdown-preview-enhanced-0.8.4\out\native\extension.js:1401:14603)
	at async bs.initPreview (c:\Users\litra\.vscode\extensions\shd101wyy.markdown-preview-enhanced-0.8.4\out\native\extension.js:1401:13164)
console.ts:137 [Extension Host] InvalidCharacterError: Invalid character
	at new DOMException (node:internal/per_context/domexception:53:5)
	at __node_internal_ (node:internal/util:526:10)
	at atob (node:buffer:1303:13)
	at e.renderer.rules.image (c:\Users\litra\.vscode\extensions\shd101wyy.markdown-preview-enhanced-0.8.4\out\native\extension.js:1083:16686)
	at g6.renderInline (c:\Users\litra\.vscode\extensions\shd101wyy.markdown-preview-enhanced-0.8.4\out\native\extension.js:313:139)
	at g6.render (c:\Users\litra\.vscode\extensions\shd101wyy.markdown-preview-enhanced-0.8.4\out\native\extension.js:314:138)
	at jC.render (c:\Users\litra\.vscode\extensions\shd101wyy.markdown-preview-enhanced-0.8.4\out\native\extension.js:316:41992)
	at Nh.parseMD (c:\Users\litra\.vscode\extensions\shd101wyy.markdown-preview-enhanced-0.8.4\out\native\extension.js:1389:1585)
	at async Nh.generateHTMLTemplateForPreview (c:\Users\litra\.vscode\extensions\shd101wyy.markdown-preview-enhanced-0.8.4\out\native\extension.js:1193:2448)
	at async bs.initPreview (c:\Users\litra\.vscode\extensions\shd101wyy.markdown-preview-enhanced-0.8.4\out\native\extension.js:1401:14603)
	at async bs.initPreview (c:\Users\litra\.vscode\extensions\shd101wyy.markdown-preview-enhanced-0.8.4\out\native\extension.js:1401:13164)
$ @ console.ts:137
$logExtensionHostMessage @ mainThreadConsole.ts:39
S @ rpcProtocol.ts:456
Q @ rpcProtocol.ts:441
M @ rpcProtocol.ts:371
L @ rpcProtocol.ts:297
(anonymous) @ rpcProtocol.ts:161
z @ event.ts:1138
fire @ event.ts:1169
fire @ ipc.net.ts:650
Y.onmessage @ localProcessExtensionHost.ts:581
```

**Comment by van-lee-fxp** [comment]
我尝试了一下，在已经已经移除了`parser.js`脚本的前提下，即使是一个新建的markdown文件，没有用到任何复杂的格式，只是加了一个标题和一点点随机的文字，然后想要import一样会报错。

**Comment by shd101wyy** [comment]
我貌似懂了。是不是 `.less` 文件里面有中文？是的话我一会儿修复一下这个 bug。

**Comment by van-lee-fxp** [comment]
有可能吧~我原来的`.less`文件里字体的名称和注释有中文。但是不太清楚为什么之后我随便写一个`@import`语句都会弹窗报错

**Comment by shd101wyy** [comment]
应该已经修复了

**Comment by van-lee-fxp** [comment]
好的，我去试试看 ---- 回复的原邮件 ----发件人Yiyi ***@***.***>发送日期2023年10月11日 08:36 ***@***.***> 抄送人F. X. ***@***.***>***@***.***>主题Re: [shd101wyy/vscode-markdown-preview-enhanced] [BUG] ***@***.***`语句导入自己的`.less`样式表时遇到异常 (Issue #1823)
应该已经修复了

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/shd101wyy/vscode-markdown-preview-enhanced/issues/1823#issuecomment-1756522817",
"url": "https://github.com/shd101wyy/vscode-markdown-preview-enhanced/issues/1823#issuecomment-1756522817",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by van-lee-fxp** [comment]
中午测试了一下，发现好像问题还是没有解决。我这次只是创建了一个简单的文档，里面的内容只有英文没有中文，样式表也是建在同级目录的，也是只有英文没有中文。然后我使用同样的方法进行预览，仍然是输入到`@import`里面的引号就报错，报错内容也没变。问题好像与样式表文件里面是否含有中文，以及markdown源文件是否含有中文都没有关联。

![Code_vilttMEBwr](https://github.com/shd101wyy/vscode-markdown-preview-enhanced/assets/146909397/2aca4e80-eaaa-4daf-b231-4ef9afbd5c3e)

报错信息如下

```
console.ts:137 [Extension Host] InvalidCharacterError: Invalid character
	at new DOMException (node:internal/per_context/domexception:53:5)
	at __node_internal_ (node:internal/util:526:10)
	at atob (node:buffer:1303:13)
	at S8t.e.renderer.rules.image (c:\Users\litra\.vscode\extensions\shd101wyy.markdown-preview-enhanced-0.8.5\out\native\extension.js:1084:16705)
	at g6.renderInline (c:\Users\litra\.vscode\extensions\shd101wyy.markdown-preview-enhanced-0.8.5\out\native\extension.js:313:139)
	at g6.render (c:\Users\litra\.vscode\extensions\shd101wyy.markdown-preview-enhanced-0.8.5\out\native\extension.js:314:138)
	at jC.render (c:\Users\litra\.vscode\extensions\shd101wyy.markdown-preview-enhanced-0.8.5\out\native\extension.js:316:41992)
	at Nh.parseMD (c:\Users\litra\.vscode\extensions\shd101wyy.markdown-preview-enhanced-0.8.5\out\native\extension.js:1390:1553)
	at async Nh.generateHTMLTemplateForPreview (c:\Users\litra\.vscode\extensions\shd101wyy.markdown-preview-enhanced-0.8.5\out\native\extension.js:1194:2448)
	at async bs.initPreview (c:\Users\litra\.vscode\extensions\shd101wyy.markdown-preview-enhanced-0.8.5\out\native\extension.js:1402:14603)
```

我尝试过，最后一个能正常使用`@import`语句的插件版本是`0.8.1`

**Comment by van-lee-fxp** [comment]
源文件——

[test.zip](https://github.com/shd101wyy/vscode-markdown-preview-enhanced/files/12865067/test.zip)

`0.8.1`版本的运行效果图——

![Code_LBg9dbLvVN](https://github.com/shd101wyy/vscode-markdown-preview-enhanced/assets/146909397/36c37957-7dee-4d10-952b-10695a6bb947)

**Comment by shd101wyy** [comment]
你现在用的是最新的 `0.8.5` 版本吗？

**Comment by van-lee-fxp** [comment]
是的，我已经升级到了`0.8.5`版本

**Comment by shd101wyy** [comment]
很明显是 `test.less` 里面字符的问题。理论上来讲 `0.8.5` 应经修复了。你试试 `test.less` 里面只写英文字符？

然后你确定你用的是 `0.8.5`？你的 vscode 版本是多少？

**Comment by van-lee-fxp** [comment]
确定的。VSCode的版本是`1.83.0`, 我现在测试用的`test.less`里面确实只有英文没有中文：
```less
.markdown-preview.markdown-preview {
    background-color: blue !important;
 }
```

**Comment by van-lee-fxp** [comment]
![Uploading Code_FWZ4L00eV3.png…]()

**Comment by van-lee-fxp** [comment]
![Code_FWZ4L00eV3](https://github.com/shd101wyy/vscode-markdown-preview-enhanced/assets/146909397/5863a914-3fa2-43f8-9ea7-55f06709e3bc)

**Comment by van-lee-fxp** [comment]
而且这个错误对话框是我一输入`@import`后面双引号里的内容就开始疯狂弹出

**Comment by van-lee-fxp** [comment]
现在知道是怎么回事了，一打开`enable typographer`这个设置项就会报错，把这个设置项关掉报错就不见了

**Comment by van-lee-fxp** [comment]
所以估计应该是typographer这个功能把默认的代码中用的直引号`"xxx"`自动换成了左右引号`“xxx”`导致的错误

**Comment by shd101wyy** [comment]
ok 我有时间看一下。非常感谢 :pray:

**Comment by van-lee-fxp** [comment]
此外还发现一个问题，现在`@import`变得只能用相对路径导入了，如果用绝对路径导入是不成功的，下面会显示一行类似这样的东西——

```
![@embedding](D:\New Homeland\Resources\Programming\Code\heti-master\_site\heti.css){embedding=""}
```

括号里写的是我尝试导入的文件的绝对路径，然后后面有个embedding表示的应该是试图嵌入的具体内容，但是这个内容没有被成功嵌入显示出来，只留下来这么一行源码。

**Comment by van-lee-fxp** [comment]
我一开始的导入就是用绝对路径的，结果提示是一段base64编码。正常如果导入遇到问题，文档中会看到一个类似代码块的区域，告诉你导入时产生的报错信息，但是我用绝对路径导入的时候，连报错信息也无法正常显示了。昨天第一次出现问题时的base64解码结果是——

```
<pre class="language-text"><code>InvalidCharacterError: Invalid character</code></pre>  
```

意思应该是在文档中插入这么一个`<pre>`元素，也就是代码块，显示`InvalidCharacter`的报错信息。但是因为绝对路径导入导致了这行报错信息都无法正确显示，才产生了文档里莫名其妙地多出一行字的现象。

**Comment by van-lee-fxp** [comment]
oh～原来是这个原因～

**Comment by shd101wyy** [comment]
0.8.6 应该已经修好了
确实是 enableTypographer 的问题。先在这个就算开启了也不会有问题了。谢谢

**Comment by van-lee-fxp** [comment]
测试过了，打开`enableTypographer`后已经正常，感谢~
